siteName: "CDDFRS Website"
collections:
  - name: "news"
    label: "News Posts"
    folder: "src/pages/news/posts"
    create: true
    fields:
      - name: "title"
        label: "Title"
        type: "string"
      - name: "date"
        label: "Date"
        type: "date"
      - name: "body"
        label: "Body"
        type: "markdown"
  - name: "pages"
    label: "Site Pages"
    folder: "src/pages"
    create: false
    fields:
      - name: "title"
        label: "Title"
        type: "string"
      - name: "body"
        label: "Body"
        type: "markdown"
  - name: "stations"
    label: "Fire Stations"
    folder: "src/pages/about/stations"
    create: true
    fields:
      - name: "name"
        label: "Station Name"
        type: "string"
      - name: "body"
        label: "Description"
        type: "markdown"