siteName: "Test Site"
collections:
  - name: "test"
    label: "Test Collection"
    folder: "src/pages/test"
    create: true
    fields:
      - name: "title"
        label: "Title"
        type: "string"
      - name: "body"
        label: "Body"
        type: "markdown"